### PR TITLE
Added Liqube Dark Code based theme

### PR DESCRIPTION
**Pull request by liqube**
Based on https://github.com/liqube/liqube-dark-vscode

Added in alphabetically, created preview image.

### CODE REVIEW

**Comment by liqube** [comment]
Includes color queried by identguide plugin.

snap20200516180744

**Comment by rxi** [comment]
Looks great, thanks!

**Comment by harikt** [comment]
Wonderful theme @liqube . And I just noticed you are the real author of the project. Thank you for the theme.

**Comment by liqube** [comment]
> 
> 
> Wonderful theme @liqube . And I just noticed you are the real author of the project. Thank you for the theme.

You're welcome! Glad you like it :)

**Pull request merged**
